### ISSUE TITLE
Typo with sign convention

### ISSUE THREAD

**Issue by YuJerryShi** [fancompute/fdfdpy#10]
https://github.com/fancompute/fdfdpy/blob/15bc317ee0a0964b6ae2336cb89b4bc4ce1ee2b5/fdfdpy/Fdfd.py#L94

https://github.com/fancompute/fdfdpy/blob/15bc317ee0a0964b6ae2336cb89b4bc4ce1ee2b5/fdfdpy/Fdfd.py#L95

The sign for "ex" and "ey" should be flipped. Otherwise, the Poynting vector you get will be the reverse of what it should be

**Comment by twhughes** [comment]
Thanks, I guessed when I first wrote it but never fixed 😨

**Comment by twhughes** [comment]
In the future, if you see a minor change like that, feel free to submit a pull request with the change and then we can just merge it into the code :)

**Comment by twhughes** [comment]
ok I fixed this.  Th Hx and Hy are ok?
