### ISSUE TITLE
Remove pyMKL as a submodule

### ISSUE THREAD

**Issue by ianwilliamson** [fancompute/fdfdpy#11]
After realizing that pyMKL can be installed with pip, I don't any reason to keep it as a submodule.

**Comment by ianwilliamson** [comment]
Needs to be added to `requirements.txt` I think.

**Comment by twhughes** [comment]
yea this should be fine after the merge.  I tested the setup.py install with a virtualenv and every module gets installed correctly without any requirements.txt or submodules

**Comment by twhughes** [comment]
merged
