### ISSUE TITLE
MKLlib error

### ISSUE THREAD

**Issue by kdotom** [fancompute/fdfdpy#18]
I attempted to run the python -m unittest test_nonlinear_solvers.py command and received the following error:

UnboundLocalError: local variable 'MKLlib' referenced before assignment

Are there any extra steps to be done?

(I installed this via "pip install fdfdpy")

**Comment by twhughes** [comment]
Hi, Do you have MKL installed?  If not try `conda install MKL` if using anaconda.  You may also want to try our `angler` package https://github.com/fancompute/angler which contains a more updated version of `fdfdpy` that you can use in the same way.  Let me know if that fixes your problem!

**Comment by kdotom** [comment]
Got it. Worked perfectly with anaconda. Thanks!

**Comment by drmcnelson** [comment]
What is the install command for MKL  someone who is not using conda?   (c.f. Fedora)

**Comment by ianwilliamson** [comment]
You should just be able to `pip` install it like so:
```
pip install mkl
pip install pymkl
```
For reference, the associated package is here: https://pypi.org/project/pyMKL/
