### ISSUE TITLE
Typo with averaging of epsilon

### ISSUE THREAD

**Issue by YuJerryShi** [fancompute/fdfdpy#9]
https://github.com/fancompute/fdfdpy/blob/15bc317ee0a0964b6ae2336cb89b4bc4ce1ee2b5/fdfdpy/Fdfd.py#L94

**Comment by YuJerryShi** [comment]
This should be "T_eps_y_inv", not "T_eps_x_inv"

**Comment by twhughes** [comment]
thanks!  Is the `ey` one correct?

**Comment by twhughes** [comment]
fixed this too
